---
- name: Install and Configure Web server
  hosts: web
  vars:
    user_name: "AJ"

  tasks:
  - name: Install Webserver using roles
    include_role:
      name: installservice
    vars:
      package_name: "httpd"
      service_name: "httpd"

  - name: Configure Webserver using roles
    include_role:
      name: configureservice
    vars:
      content: "{{ ansible_distribution }} {{ user_name }}"
      dest: /var/www/html/index.html
      owner: training
      group: training
      mode: '0755'
      service: httpd

- name: Install and Configure InfluxDB
  hosts: db

  tasks:
  - name: Install InfluxDB using roles
    include_role:
      name: installservice
    vars:
      reponame: influxdb
      baseurl: https://repos.influxdata.com/rhel/7/x86_64/stable/
      gpgkey_name: https://repos.influxdata.com/influxdb.key
      package_name: influxdb
      service_name: influxdb

  - name: Configure InfluxDB using roles
    include_role:
      name: configureservice
    vars:
      src: /home/training/day2/AnsibleTeamGroupWorkshop/influxdb.conf
      dest: /etc/influxdb/influxdb.conf
      owner: root
      group: root
      mode: '0644'
      service: influxdb

- name: Add database and User using control node
  hosts: control
  vars_files:
    - vars.yaml

  tasks:
  - name: install infludb-sdk using pip3
    pip:
      name: influxdb
      executable: pip3

  - name: create database in db server
    influxdb_database:
      database_name: server_metrics
      hostname: 10.240.0.4

  - name: create user in db server for server_metrics
    influxdb_user:
      user_name: server
      user_password: "{{ db_password }}"
      hostname: 10.240.0.4
      grants:
        - database: "server_metrics"
          privilege: "all"


- name: Install and Configure Grafana
  hosts: monitor

  tasks:
  - name: install grafana using roles
    include_role:
      name: installservice
    vars:
      reponame: "grafana"
      baseurl: https://packages.grafana.com/oss/rpm
      gpgkey_name: https://packages.grafana.com/gpg.key
      package_name: "grafana"
      service_name: "grafana-server"

- name: Install servermetrics.py
  hosts: nodes
  vars_files:
    - vars.yaml

  tasks:
  - name: Install servermetrics.py using roles
    include_role:
      name: servermetrics
    vars:
      ip: "10.240.0.4"
      port: "8086"
      user: "server"
      password: "{{ db_password }}"
      measurement: "server_metrics"
      path: /home/training
      owner: "training"
      group: "training"
